const order = "ORDER";

const CREATE_ORDER_REQUEST_TYPE = `${order}/CREATE_REQUEST`;
const CREATE_ORDER_REQUEST_SUCCESS_TYPE = `${order}/CREATE_REQUEST_SUCCESS`;
const CREATE_ORDER_REQUEST_FAILED_TYPE = `${order}/CREATE_REQUEST_FAILED`;

//export const GET_ORDER_INFO_REQUEST = `${order}/GET_ORDER_INFO_REQUEST`;
//export const GET_ORDER_INFO_REQUEST_SUCCESS = `${order}/CREATE_REQUEST_SUCCESS`;
//export const GET_ORDER_INFO_REQUEST_FAILED = `${order}/CREATE_REQUEST_FAILED`;

export const CREATE_ORDER_REQUEST: typeof CREATE_ORDER_REQUEST_TYPE = CREATE_ORDER_REQUEST_TYPE;
export const CREATE_ORDER_REQUEST_SUCCESS: typeof CREATE_ORDER_REQUEST_SUCCESS_TYPE = CREATE_ORDER_REQUEST_SUCCESS_TYPE;
export const CREATE_ORDER_REQUEST_FAILED: typeof CREATE_ORDER_REQUEST_FAILED_TYPE = CREATE_ORDER_REQUEST_FAILED_TYPE;